name: flutter_datetime_picker_sharp
description: A date time picker for flutter, you can choose date / time / date&time in English Dutch and Chinese, and you can also customize your own picker content
version: 2.1.0
homepage: https://github.com/fa0311/flutter_datetime_picker_sharp

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
